version: '3'
services:
  myapp:
    image: kavin1995/projectquality:latest
    container_name: dataquality
    ports:
      - "8082:8082"
    environment:
      - DEBUG=true
    volumes:
      - ./app:/app
